"""add name to user

Revision ID: d14b28154107
Revises: 
Create Date: 2025-05-28 18:14:20.410171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14b28154107'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_preferences', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'user_preferences', type_='foreignkey')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    # ### end Alembic commands ###
