"""add custom_water_goal to user_preferences

Revision ID: fcf9e07eda0c
Revises: 9e7978ad887f
Create Date: 2025-06-01 21:56:22.239280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf9e07eda0c'
down_revision: Union[str, None] = '9e7978ad887f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('custom_water_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'custom_water_goal')
    # ### end Alembic commands ###
